### ISSUE TITLE
Missing docker dependancy

### ISSUE THREAD

**Issue by kroy-the-rabbit** [gandazgul/k8s-infrastructure#23]
Docker fails to install due to a missing dependancy.  This puts all the docker related stuff in configNode.sh in a bad state

```
error: Failed dependencies:
	libcgroup is needed by docker-ce-17.03.2.ce-1.fc25.x86_64
```

**Comment by gandazgul** [comment]
Interesting, I haven't run into this issue before. Were you on a fresh install of Fedora? what version?

**Comment by kroy-the-rabbit** [comment]
Operating System: Fedora 29 (Server Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:29
            Kernel: Linux 4.20.8-200.fc29.x86_64
      Architecture: x86-64

**Comment by gandazgul** [comment]
Cool thanks, I'll look into it.

**Comment by gandazgul** [comment]
So I tested it on a clean install of Fedora 28 again and it doesn't give any errors so I'm guessing something changed with Fedora 29.

Can you try installing docker 18.06 since its now supported and see if that works? 

New list of supported docker versions in 1.13 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#external-dependencies

It also seems Docker 1.13.1 is supported which is the version available in Fedora 28, maybe it can be installed in Fedora 29 as well?

Let me know how it goes

**Comment by gandazgul** [comment]
I got around to test this on Fedora 29 and updated the install scripts. Check out the PR #31

**Comment by gandazgul** [comment]
I tested again in Fedora 29 with current master and is working. @kroy-the-rabbit if you have other issues dont hesitate to open an issue. Thank you
